version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.4-fpm
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
