version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: .
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bm
    ports:
      - "3306:3306"
